= Setting up multiple clusters for local FE development
:experimental:

Sometimes, you need to be able to do local development on the front-end
app, while having multiple clusters available in your environment. For
instance, when working on the Clusters section of the FE app.

== Instructions

In one terminal window: +
Create a cluster and deploy an appropriate a StackRox backend to it.

. Run `teardown` to make sure you aren't running StackRox locally.
. Provision a cluster of your liking (e.g. a GKE cluster)
. Connect your local machine to this cluster.
 .. `yarn connect <clusterName>` (the cluster name is the one
you gave it when you created it, like _mytestcluster_)
. Export the StackRox image tag you wish to deploy (optional, if you
need code not yet on master) +
`export MAIN_IMAGE_TAG='<image-tag>'`
. Set up a load balancer by setting the env. variable by running  +
`export LOAD_BALANCER=lb`
. Deploy to the GKE cluster +
`yarn deploy`
. Copy and save the admin password that is generated by the deploy
command +
(will look something like _5bKX7BMGhgrWodwkrMefRAmek_)
. Find the external IP for this central cluster +
`kubectl -n stackrox get svc central-loadbalancer` +
example output:+++<div class="code panel pdl" style="border-width: 1px;">+++``` NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE central-loadbalancer LoadBalancer 10.15.254.128 104.155.188.55 443:31140/TCP 77m ```+++</div>+++
. Start port-forwarding +
`yarn forward`

In a second terminal window, also with `rox/ui/` as the current working
directory: +
Connect your local frontend to it, and use your frontend to add a 2nd
cluster.

. Check out the branch you are using for front-end development, and
start your local dev frontend. +
`yarn start`
. Login with the username *admin* and the password you saved from
the output of the deploy script above.
. Go to the menu:Platform Configuration[Clusters], click on *New
Cluster*, give the new cluster a name, and for *Central API
Endpoint*, enter the external IP address of the load balancer you
found above.
. Click the Next button, and download the YAML file and keys.

In a 3rd terminal window, +
Deploy the sensor to your local docker-desktop cluster.

. Switch to the directory where you downloaded the YAML/keys zip
file. +
(e.g., `cd ~/Downloads`)
. Unzip the archive. (Filename will be like
`sensor-<clustername>.zip`) +
`unzip sensor-baz.zip`
. Switch back to docker-desktop context +
`kubectl config use-context docker-desktop`
. Run the script to deploy the sensor to your local docker-desktop
cluster +
`./sensor-baz/sensor.sh`
