= Building on Linux
:toc:

== Fedora/RHEL (and others)

This guide is tailored towards RHEL, but it should work on other distros as well. +
You might need to

=== (Optional) Change default shell to bash

The directions here are given for a bash shell, though they should also work
for zsh. If you are using a Red Hat laptop the default shell should be bash. If
it is not and you want to change it to bash you can do the following step.

. Launch the Terminal app (or your terminal emulator of choice)
. Change default shell to bash
+
----
 % chsh -s /bin/bash
----

. You'll be prompt to enter your password. Then, close the terminal and reopen it. The terminal will come back with bash prompt "$".

=== Install Development Tools

. Launch the Terminal app
. Run the command to install the group Development Tools:
+
----
 $ sudo dnf groupinstall 'Development Tools'
----

==== Verify

. Run this command:
+
----
 $ gcc --version
----

. Verify you see the following:
+
----
 gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)
----

=== Install Docker

. Follow the directions https://docs.docker.com/engine/install/centos/[here] which are also summarized below.
+
[,bash]
----
 sudo yum install -y yum-utils
 sudo yum-config-manager \
     --add-repo \
     https://download.docker.com/linux/centos/docker-ce.repo
 sudo yum install docker-ce docker-ce-cli containerd.io
 sudo groupadd docker
 sudo usermod -aG docker $USER
----

. Start the docker daemon and make it so that it start automatically at boot.
+
----
 sudo systemctl enable docker
----

. Restarting you computer may be needed in order for the next step to work.

==== Verify

. Run this command:
+
----
 $ docker run --rm hello-world
----

. Verify you see output something like the following:
+
----
 (...)
 Hello from Docker!
 (...)
----

=== Install minikube

. Follow the directions https://www.unixarena.com/2019/05/how-to-deploy-kubernetes-minikube-on-rhel-centos.html/[here]. +
The steps are also given below:
+
[,bash]
----
 sudo yum -y install qemu-kvm libvirt libvirt-daemon-kvm
 sudo systemctl enable libvirtd
 sudo systemctl start libvirtd

 # Optionally check that your laptop supports VT technology.
 virt-host-validate

 # Check that firewalld is running
 systemctl status firewalld
----

. Create a file at `/etc/yum.repos.d` with the following contents
+
[,ini]
----
 [kubernetes]
 name=Kubernetes
 baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
 enabled=1
 gpgcheck=1
 repo_gpgcheck=1
 gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
----

. Install and set up kubectl and additional tooling
+
----
 sudo yum -y install kubectl
 wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 -O minikube
 wget https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2
 chmod 755 minikube docker-machine-driver-kvm2
 sudo mv minikube docker-machine-driver-kvm2 /usr/local/bin/
----

=== Install Go

. Please see https://github.com/stackrox/stackrox/blob/master/EXPECTED_GO_VERSION[here] for the latest version used at StackRox that you should download. +
Follow the directions https://golang.org/doc/install[here] to install Go.

==== Verify

. Run the command to inspect the version of Go that was just installed. It should be what you expect:
+
----
 $ go version

 go version go1.16.5 linux/amd64 # This should reflect the version you just installed
----

=== Install npm

. Install npm
+
----
 sudo yum install npm
 sudo npm install --global yarn
----

. Install nvm
+
----
 curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
 source ~/.bashrc
----

. Update node
+
----
 nvm install 12.13.0
----

==== Verify

....
```
node --version

v12.13.0 # This should match the version you installed with nvm
```
....

=== Install bats

https://centos.pkgs.org/7/epel-x86_64/bats-0.4.0-1.20141016git3b33a5a.el7.noarch.rpm.html[This] is a helpful resource

 ```
 wget https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/b/bats-0.4.0-1.20141016git3b33a5a.el7.noarch.rpm
 sudo rpm -Uvh bats-0.4.0-1.20141016git3b33a5a.el7.noarch.rpm
 ```

=== Install gradle

. Install gradle 6.7.1. Get it from https://gradle.org/releases/[here]. Use the binary version.
. Add the following to your .bashrc file
+
----
 export PATH=$PATH:<PATH_TO_GRADLE>/gradle-6.7.1/bin
 source ~/.bashrc
----

=== Install Helm

. Follow the directions https://helm.sh/docs/intro/install/[here] which are summarized below.
. Download the correct version of helm https://github.com/helm/helm/releases[here]
+
----
 $ tar -zxvf helm-v3.6.2-linux-amd64.tar.gz
 $ cd linux-amd64/ #Or wherever your helm binary is
 $ sudo cp helm /usr/local/bin/
----

==== Verify

. Run the command to inspect the version of Helm that was just installed
+
----
 $ helm version
 version.BuildInfo{Version:"v3.6.2", (...)}
----

=== Install Workflow Scripts

. Clone the workflow repository:
+
[,bash]
----
 # If you choose to follow the opinionated golang installation of putting everything into a "go" folder:
 $ mkdir -p ~/go/src/github.com/stackrox/
 $ cd ~/go/src/github.com/stackrox/
 $ git clone git@github.com:stackrox/workflow.git
----

. Follow the steps in the https://github.com/stackrox/workflow/blob/master/README.md[repo's README]

==== Verify

. Run roxhelp in the terminal to verify correct installation.
+
----
 $ roxhelp

 Usage:
 /Users/ross/go/src/github.com/stackrox/workflow/bin/roxhelp <command_name> (to print help for command <command_name>)
 /Users/ross/go/src/github.com/stackrox/workflow/bin/roxhelp --list-all (to list all available Rox commands)
----

// end of rhel end of fedora /////////////////////////////////////////////////////

== Build on Nix

`Nix` is both a package manager and a programming language, in which derivations for
said package manager are written. While `Nix` was originally developed for `NixOS`, it
supports any Linux distribution as well as macOS. The goal of the `Nix` project is
to provide declarative and reproducible build environments.

https://github.com/stackrox/stackrox-env[Stackrox-env] provides a development environment,
which includes all necessary tools to contribute to the https://github.com/stackrox/stackrox[Stackrox project] regardless
of whether Linux or macOS is the underlying operating system. This approach represents an
alternative to the imperative approaches outlined in the xref:getting-started-linux.adoc[Linux] and xref:getting-started-darwin.adoc[macOS] guides.
The `Nix` environment provides the following advantages over the conventional setup:

* `infrastructure-as-code`: Changes to the environment are tracked by git and must pass a continuous integration pipeline.
* A `git pull` is sufficient to keep the environment in sync.
* The `Nix store` hermetically stores binaries, libraries and all dependencies. No pollution on a system level.
* Rollbacks become trivial by reverting to an older git revision.

=== Install Nix

Follow the https://nixos.org/download.html#download-nix[instructions] to install `Nix` on your operating system.

=== Download Stackrox Nix environment

Follow the https://github.com/stackrox/stackrox-env[instructions] to download the
Stackrox Nix environment. You may either choose to set the environment globally in your system
by https://github.com/stackrox/stackrox-env#login-shell[sourcing the environment in your login shell], or
source the environment locally using the https://github.com/stackrox/stackrox-env#direnv-integration[Direnv integration].

=== Install workflow scripts (optional)

. Clone the workflow repository:
+
[,bash]
----
 # If you choose to follow the opinionated golang installation of putting everything into a "go" folder:
 $ mkdir -p ~/go/src/github.com/stackrox/
 $ cd ~/go/src/github.com/stackrox/
 $ git clone git@github.com:stackrox/workflow.git
----

. Follow the steps in the https://github.com/stackrox/workflow/blob/master/README.md[repo's README]

==== Verify

. Run roxhelp in the terminal to verify correct installation.
+
----
 $ roxhelp

 Usage:
 /Users/ross/go/src/github.com/stackrox/workflow/bin/roxhelp <command_name> (to print help for command <command_name>)
 /Users/ross/go/src/github.com/stackrox/workflow/bin/roxhelp --list-all (to list all available Rox commands)
----

