= Getting started with Nix

`Nix` is both a package manager and a programming language, in which derivations for
said package manager are written. While `Nix` was originally developed for `NixOS`, it
supports any Linux distribution as well as macOS. The goal of the `Nix` project is
to provide declarative and reproducible build environments.

https://github.com/stackrox/stackrox-env[Stackrox-env] provides a development environment,
which includes all necessary tools to contribute to the https://github.com/stackrox/stackrox[Stackrox project] regardless
of whether Linux or macOS is the underlying operating system. This approach represents an
alternative to the imperative approaches outlined in the xref:getting-started-linux.adoc[Linux] and xref:getting-started-darwin.adoc[macOS] guides.
The `Nix` environment provides the following advantages over the conventional setup:

* `infrastructure-as-code`: Changes to the environment are tracked by git and must pass a continuous integration pipeline.
* A `git pull` is sufficient to keep the environment in sync.
* The `Nix store` hermetically stores binaries, libraries and all dependencies. No pollution on a system level.
* Rollbacks become trivial by reverting to an older git revision.

== Install Nix

Follow the https://nixos.org/download.html#download-nix[instructions] to install `Nix` on your operating system.

== Download Stackrox Nix environment

Follow the https://github.com/stackrox/stackrox-env[instructions] to download the
Stackrox Nix environment. You may either choose to set the environment globally in your system
by https://github.com/stackrox/stackrox-env#login-shell[sourcing the environment in your login shell], or
source the environment locally using the https://github.com/stackrox/stackrox-env#direnv-integration[Direnv integration].

== Install workflow scripts (optional)

. Clone the workflow repository:
+
[,bash]
----
 # If you choose to follow the opinionated golang installation of putting everything into a "go" folder:
 $ mkdir -p ~/go/src/github.com/stackrox/
 $ cd ~/go/src/github.com/stackrox/
 $ git clone git@github.com:stackrox/workflow.git
----

. Follow the steps in the https://github.com/stackrox/workflow/blob/master/README.md[repo's README]

=== Verify

. Run roxhelp in the terminal to verify correct installation.
+
----
 $ roxhelp

 Usage:
 /Users/ross/go/src/github.com/stackrox/workflow/bin/roxhelp <command_name> (to print help for command <command_name>)
 /Users/ross/go/src/github.com/stackrox/workflow/bin/roxhelp --list-all (to list all available Rox commands)
----
